/** @format */

const labels = {
  login: "Log In",
  noInternetConnection: "No internet connection at the moment!",
  welcomeBackAdmin: "Welcome back admin!",
  enterTheEmail: "Enter the email address and password to login",
  enterEmail: "Enter Email",
  enterPassword: "Enter Password",
  rememberMe: "Remember Me",
  dashboard: "Dashboard",
  specials: "Specials",
  notification: "Notification",
  feedback: "Feedback",
  adminName: "Admin Name",
  Sno: "#",
  description: "description",
  status: "status",
  actions: "actions",
  title: "title",
  search: "Search",
  specialCount: "26",
  addNewSpecial: "Add New Special",
  uploadImage: "Upload Image",
  DragAndDropHere: "Drag and drop here or Browse",
  typeTitleHere: "Type Title Here",
  typeUrlHere: "Type URL Here",
  typeDescriptionHere: "Type Discription Here..",
  addNewStore: "Add New Store",
  location: "location",
  url: "url",
  youHaveNotAddedAnySpecial: "You’ve not added any special",
  addNow: "Add Now",
  callToAction: "Call To Action",
  callToActionLink: "https://www.calimero...",
  sendNotification: "Send Notification",
  sendNotification: "Send Notification",
  typeHere: "Type Here..",
  notificationDetail: "Notification Detail",
  notificationHeading: "Sed do eiusmod tempor incididunt.",
  notificationDescription:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  notificationUrl: "https://www.calimero.co.nz/",
  youHaveNotAddedNotification: "You’ve not sent any notification",
  sendNow: "Send Now",
  youhavenotrecievedfeedback: "You’ve not received any feedback",
  phoneNo: "Phone No",
  emailAddress: "Email Address",
  userName: "User Name",
  rating: "Rating",
  feedbackDetail: "Feedback Detail",
  loginSuccess: "Login SuccessFul!",
  logoutSuccess: "Logout SuccessFul!",
  store: "Store",
  image: "Image",
  addStore: "Add Store",
  storeName: "Store Name",
  typeStoreName: "Type Store Name",
  typeLocationHere: "Type Location Here..",
  visibility: "visibility",
  specialAddedSuccess: "Special Item Added Successful!",
  pleaseSelectImagetoUpload: "Please Select Image to upload!",
  remove: "Remove",
  addNotification: "Add Notification",
  typeNotificationTitle: "Type notification title here..",
  areYouWantToDeleteThisStore: "Are you sure you want to delete this store?",
  areYouWantToDeleteThisSpecialItem:
    "Are you sure you want to delete this special item?",
  youhavenotaddedanystores: "You have not added any store.",
  areYouSureYouWantToDeleteNotification:
    "Are you sure you want to delete this notification?",
  prev: "prev",
  next: "next",
  editStore: "Edit Store",
  editSpecialItem: "Edit Special Item",
  latitude: "latitude",
  longitude: "longitude",
  typeLatitude: "Type latitude here..",
  typeLongitude: "Type longitude here..",
  OrderUrl: "Order Url",
  viewStore: "View Store",
  viewSpecialItem: "View Special Item",
  selectLocation: "Select location",
};

export default labels;
